# Módulo 5 Tarefa 1
## Base de nascidos vivos do DataSUS
O DataSUS disponibiliza diversos arquivos de dados com relação a seus segurados, conforme a [lei da transparência de informações públicas](https://www.sisgov.com/transparencia-acesso-informacao/#:~:text=A%20Lei%20da%20Transpar%C3%AAncia%20(LC,em%20um%20site%20na%20internet.). 

Essas informações podem ser obtidas pela internet [aqui](http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1). Como o processo de obtenção desses arquivos foge um pouco do nosso escopo, deixamos o arquivo ```SINASC_RO_2019.csv``` já como vai ser encontrado no DataSUS. O dicionário de dados está no arquivo ```estrutura_sinasc_para_CD.pdf``` (o nome do arquivo tal qual no portal do DataSUS).

### Nosso objetivo
Queremos deixar uma base organizada para podermos estudar a relação entre partos com risco para o bebê e algumas condições como tempo de parto, consultas de pré-natal etc.


#### Preparação da base
1. Carregue a base 'SINASC_RO_2019.csv'. Conte o número de registros e o número de registros não duplicados da base. Dica: você aprendeu um método que remove duplicados, encadeie este método com um outro método que conta o número de linhas. Há linhas duplicadas?

In [1]:
import pandas as pd
import requests
import numpy as np

# 1) seu código aqui
sinasc = pd.read_csv('SINASC_RO_2019.csv')
print(sinasc.shape)
sinasc.drop_duplicates().shape
# Não há duplicados

(27028, 69)


(27028, 69)

In [2]:
sinasc.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

2. Conte o número de valores *missing* por variável.  

In [3]:
# 2) seu código aqui
sinasc.isnull().sum()

ORIGEM          0
CODESTAB      115
CODMUNNASC      0
LOCNASC         0
IDADEMAE        0
             ... 
munResUf        0
munResLat       1
munResLon       1
munResAlt       1
munResArea      1
Length: 69, dtype: int64

3. Ok, no item anterior você deve ter achado pouco prático ler a informação de tantas variáveis, muitas delas nem devem ser interesantes. Então crie uma seleção dessa base somente com as colunas que interessam. São elas:
``` 
['LOCNASC', 'IDADEMAE', 'ESTCIVMAE', 'ESCMAE', 'QTDFILVIVO', 
    'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APGAR5'] 
```
Refaça a contagem de valores *missings*.  

In [4]:
# 3) seu código aqui
sinasc_1 = sinasc[['LOCNASC', 'IDADEMAE', 'ESTCIVMAE', 'ESCMAE', 'QTDFILVIVO', 
    'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APGAR5']]

In [5]:
sinasc_1.isnull().sum()

LOCNASC          0
IDADEMAE         0
ESTCIVMAE      317
ESCMAE         312
QTDFILVIVO    1573
GESTACAO      1232
GRAVIDEZ        79
CONSULTAS        0
APGAR5         103
dtype: int64

4. Apgar é uma *nota* que o pediatra dá ao bebê quando nasce de acordo com algumas características associadas principalmente à respiração. Apgar 1 e Apgar 5 são as notas 1 e 5 minutos do nascimento. Apgar5 será a nossa variável de interesse principal. Então remova todos os registros com Apgar5 não preenchido. Para esta seleção, conte novamente o número de linhas e o número de *missings*. 

In [6]:
# 4) seu código aqui
sinasc_1['APGAR5'].dropna()
print(sinasc_1.shape)

(27028, 9)


In [7]:
sinasc_2 = sinasc_1[~sinasc_1['APGAR5'].isna()]

In [8]:
sinasc_2 

LOCNASC  IDADEMAE  ESTCIVMAE           ESCMAE  QTDFILVIVO  \
0            1        19        5.0      8 a 11 anos         0.0   
1            1        29        2.0      8 a 11 anos         1.0   
2            1        37        9.0      8 a 11 anos         2.0   
3            1        30        5.0  12 anos ou mais         0.0   
4            1        30        2.0      8 a 11 anos         1.0   
...        ...       ...        ...              ...         ...   
27023        1        32        2.0  12 anos ou mais         1.0   
27024        1        19        1.0      8 a 11 anos         0.0   
27025        1        24        2.0      8 a 11 anos         0.0   
27026        1        21        2.0      8 a 11 anos         1.0   
27027        1        18        5.0      8 a 11 anos         1.0   

              GESTACAO GRAVIDEZ  CONSULTAS  APGAR5  
0      37 a 41 semanas    Única          4    10.0  
1      37 a 41 semanas    Única          4     9.0  
2      37 a 41 semanas    Única          4    10.0  
3      37 a 41 semanas    Única          3    10.0  
4      37 a 41 semanas    Única          4    10.0  
...                ...      ...        ...     ...  
27023  32 a 36 semanas    Única          4     9.0  
27024  37 a 41 semanas    Única          4     9.0  
27025  37 a 41 semanas    Única          4    10.0  
27026  32 a 36 semanas    Única          4     9.0  
27027  37 a 41 semanas    Única          4     8.0  

[26925 rows x 9 columns]

In [9]:
print(sinasc_2.shape)

(26925, 9)


In [10]:
sinasc_2.isnull().sum()

LOCNASC          0
IDADEMAE         0
ESTCIVMAE      315
ESCMAE         310
QTDFILVIVO    1566
GESTACAO      1216
GRAVIDEZ        76
CONSULTAS        0
APGAR5           0
dtype: int64

5. observe que as variáveis ```['ESTCIVMAE', 'CONSULTAS']``` possuem o código ```9```, que significa *ignorado*. Vamos assumir que o não preenchido é o mesmo que o código ```9```.<br>

In [11]:
# 5) seu código aqui
sinasc_2.loc[sinasc_2['ESTCIVMAE'] == 9, 'ESTCIVMAE'] = np.nan

In [12]:
sinasc_2.loc[sinasc_2['CONSULTAS'] == 9, 'CONSULTAS'] = np.nan

In [13]:
sinasc_2.isnull().sum()

LOCNASC          0
IDADEMAE         0
ESTCIVMAE      459
ESCMAE         310
QTDFILVIVO    1566
GESTACAO      1216
GRAVIDEZ        76
CONSULTAS       50
APGAR5           0
dtype: int64

6. Substitua os valores faltantes da quantitativa (```QTDFILVIVO```) por zero.  

In [14]:
# 6) Seu código aqui 
sinasc_2['QTDFILVIVO'].unique()

array([ 0.,  1.,  2.,  3., nan,  4.,  6.,  5.,  7., 12.,  9., 11.,  8.,
       30., 10., 14.])

In [15]:
sinasc_2['QTDFILVIVO'] = sinasc_2['QTDFILVIVO'].fillna(0)

C:\Users\Roseane\AppData\Local\Temp\ipykernel_2268\510684087.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sinasc_2['QTDFILVIVO'] = sinasc_2['QTDFILVIVO'].fillna(0)


In [16]:
sinasc_2['QTDFILVIVO'].unique()

array([ 0.,  1.,  2.,  3.,  4.,  6.,  5.,  7., 12.,  9., 11.,  8., 30.,
       10., 14.])

In [17]:
sinasc_2.isnull().sum()

LOCNASC          0
IDADEMAE         0
ESTCIVMAE      459
ESCMAE         310
QTDFILVIVO       0
GESTACAO      1216
GRAVIDEZ        76
CONSULTAS       50
APGAR5           0
dtype: int64

7. Das restantes, decida que valor te parece mais adequado (um 'não preenchido' ou um valor 'mais provável' como no item anterior) e preencha. Justifique. Lembre-se de que tratamento de dados é trabalho do cientista, e que estamos tomando decisões a todo o momento - não há necessariamente certo e errado aqui.  

A variável escolhida para a exclusão dos dados faltantes foi o Estado Civil da Mãe, pois entendeu-se que apesar de ser um 
dado importante para se conhecer melhor as mulheres mais atendidas nesse sistema, não é um dado que de fato defina ou classifique o perfil dessas mulheres. Nesse caso, ao invés de deixar como dado faltante, optou-se por inserir o valor 9 (Ignorado).

In [18]:
# 7) seu código aqui
sinasc_2['ESTCIVMAE'].unique()

array([ 5.,  2., nan,  1.,  4.,  3.])

In [19]:
sinasc_2['ESTCIVMAE'] = sinasc_2['ESTCIVMAE'].fillna(9)

C:\Users\Roseane\AppData\Local\Temp\ipykernel_2268\92101576.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sinasc_2['ESTCIVMAE'] = sinasc_2['ESTCIVMAE'].fillna(9)


In [20]:
sinasc_2.isnull().sum()

LOCNASC          0
IDADEMAE         0
ESTCIVMAE        0
ESCMAE         310
QTDFILVIVO       0
GESTACAO      1216
GRAVIDEZ        76
CONSULTAS       50
APGAR5           0
dtype: int64

In [21]:
sinasc_2['ESTCIVMAE'].unique()

array([5., 2., 9., 1., 4., 3.])

8. O Apgar possui uma classificação indicando se o bebê passou por asfixia:
- Entre 8 e 10 está em uma faixa 'normal'. 
- Entre 6 e 7, significa que o recém-nascido passou por 'asfixia leve'. 
- Entre 4 e 5 significa 'asfixia moderada'.
- Entre 0 e 3 significa 'asfixia severa'.  

Crie uma categorização dessa variável com essa codificação e calcule as frequências dessa categorização.  
<br>

In [22]:
# 8) seu código aqui
sinasc_2['APGAR5'].unique()

array([10.,  9.,  7.,  0.,  8.,  4.,  3.,  6.,  5.,  2.,  1.])

In [23]:
sinasc_2.loc[sinasc_2['APGAR5'] >= 8, 'CLASAPGAR5'] = 'normal'
sinasc_2.loc[(sinasc_2['APGAR5'] >= 6) & (sinasc_2['APGAR5'] < 8), 'CLASAPGAR5'] = 'asfixia leve'
sinasc_2.loc[(sinasc_2['APGAR5'] >= 4) & (sinasc_2['APGAR5'] < 6 ), 'CLASAPGAR5'] = 'asfixia moderada'
sinasc_2.loc[sinasc_2['APGAR5'] < 4, 'CLASAPGAR5'] = 'asfixia severa'

C:\Users\Roseane\AppData\Local\Temp\ipykernel_2268\2991175448.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sinasc_2.loc[sinasc_2['APGAR5'] >= 8, 'CLASAPGAR5'] = 'normal'


In [24]:
sinasc_2

LOCNASC  IDADEMAE  ESTCIVMAE           ESCMAE  QTDFILVIVO  \
0            1        19        5.0      8 a 11 anos         0.0   
1            1        29        2.0      8 a 11 anos         1.0   
2            1        37        9.0      8 a 11 anos         2.0   
3            1        30        5.0  12 anos ou mais         0.0   
4            1        30        2.0      8 a 11 anos         1.0   
...        ...       ...        ...              ...         ...   
27023        1        32        2.0  12 anos ou mais         1.0   
27024        1        19        1.0      8 a 11 anos         0.0   
27025        1        24        2.0      8 a 11 anos         0.0   
27026        1        21        2.0      8 a 11 anos         1.0   
27027        1        18        5.0      8 a 11 anos         1.0   

              GESTACAO GRAVIDEZ  CONSULTAS  APGAR5 CLASAPGAR5  
0      37 a 41 semanas    Única        4.0    10.0     normal  
1      37 a 41 semanas    Única        4.0     9.0     normal  
2      37 a 41 semanas    Única        4.0    10.0     normal  
3      37 a 41 semanas    Única        3.0    10.0     normal  
4      37 a 41 semanas    Única        4.0    10.0     normal  
...                ...      ...        ...     ...        ...  
27023  32 a 36 semanas    Única        4.0     9.0     normal  
27024  37 a 41 semanas    Única        4.0     9.0     normal  
27025  37 a 41 semanas    Única        4.0    10.0     normal  
27026  32 a 36 semanas    Única        4.0     9.0     normal  
27027  37 a 41 semanas    Única        4.0     8.0     normal  

[26925 rows x 10 columns]

In [25]:
sinasc_2['CLASAPGAR5'].unique()

array(['normal', 'asfixia leve', 'asfixia severa', 'asfixia moderada'],
      dtype=object)

In [26]:
pd.get_dummies(sinasc_2['CLASAPGAR5'] == 'normal').sum()
# 'normal' aparece 26463 vezes

False      462
True     26463
dtype: int64

In [27]:
pd.get_dummies(sinasc_2['CLASAPGAR5'] == 'asfixia leve').sum()
# 'asfixia leve' aparece 320 vezes

False    26605
True       320
dtype: int64

In [28]:
pd.get_dummies(sinasc_2['CLASAPGAR5'] == 'asfixia severa').sum()
# 'asfixia severa' aparece 74 vezes

False    26851
True        74
dtype: int64

In [29]:
pd.get_dummies(sinasc_2['CLASAPGAR5'] == 'asfixia moderada').sum()
# 'asfixia moderada' aparece 68 vezes

False    26857
True        68
dtype: int64

9. Renomeie as variáveis para que fiquem no *snake case*, ou seja, em letras minúsculas, com um *underscore* entre as palavras. Dica: repare que se você não quiser criar um *dataframe* novo, você vai precisar usar a opção ```inplace = True```.

In [55]:
# 9) seu código aqui
variaveis = ['LOC_NASC', 'IDADE_MAE', 'EST_CIV_MAE', 'ESC_MAE', 'QTD_FIL_VIVO', 
    'GESTACAO', 'GRAVIDEZ', 'CONSULTAS', 'APG_AR5', 'CLAS_APG_AR5']

In [56]:
i = 0
variaveis_minusculas = []

for i in range (len (variaveis)):
    a = variaveis[i].lower()
    variaveis_minusculas.append(a)
    
variaveis_minusculas

['loc_nasc',
 'idade_mae',
 'est_civ_mae',
 'esc_mae',
 'qtd_fil_vivo',
 'gestacao',
 'gravidez',
 'consultas',
 'apg_ar5',
 'clas_apg_ar5']

In [57]:
sinasc_2.columns = variaveis_minusculas

In [58]:
sinasc_2

loc_nasc  idade_mae  est_civ_mae          esc_mae  qtd_fil_vivo  \
0             1         19          5.0      8 a 11 anos           0.0   
1             1         29          2.0      8 a 11 anos           1.0   
2             1         37          9.0      8 a 11 anos           2.0   
3             1         30          5.0  12 anos ou mais           0.0   
4             1         30          2.0      8 a 11 anos           1.0   
...         ...        ...          ...              ...           ...   
27023         1         32          2.0  12 anos ou mais           1.0   
27024         1         19          1.0      8 a 11 anos           0.0   
27025         1         24          2.0      8 a 11 anos           0.0   
27026         1         21          2.0      8 a 11 anos           1.0   
27027         1         18          5.0      8 a 11 anos           1.0   

              gestacao gravidez  consultas  apg_ar5 clas_apg_ar5  
0      37 a 41 semanas    Única        4.0     10.0       normal  
1      37 a 41 semanas    Única        4.0      9.0       normal  
2      37 a 41 semanas    Única        4.0     10.0       normal  
3      37 a 41 semanas    Única        3.0     10.0       normal  
4      37 a 41 semanas    Única        4.0     10.0       normal  
...                ...      ...        ...      ...          ...  
27023  32 a 36 semanas    Única        4.0      9.0       normal  
27024  37 a 41 semanas    Única        4.0      9.0       normal  
27025  37 a 41 semanas    Única        4.0     10.0       normal  
27026  32 a 36 semanas    Única        4.0      9.0       normal  
27027  37 a 41 semanas    Única        4.0      8.0       normal  

[26925 rows x 10 columns]